# Generated by Django 4.2.3 on 2023-07-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_academicdegree_options_and_more"),
        ("user", "0002_remove_user_custom_field_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="academicDegree",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.academicdegree",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="academicTitle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.academictitle",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.position",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ticket",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.ticket"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ticketStatus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.ticketstatus",
            ),
        ),
    ]
