# Generated by Django 4.2.3 on 2023-07-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_academicdegree_user_academictitle_user_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ticketStatus",
        ),
    ]
