# Generated by Django 4.2.3 on 2023-07-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_user_vkrhours_user_id"),
        ("user", "0005_user_educationbase"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vkrHours",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.vkrhours",
            ),
        ),
    ]
