# Generated by Django 4.2.3 on 2023-07-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_timenorm"),
        ("user", "0008_remove_user_vkrhours"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="studentGroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.studentgroup",
            ),
        ),
    ]
