# Generated by Django 4.2.3 on 2023-07-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_studentgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="number_student_book",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
