# Generated by Django 4.2.3 on 2023-07-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_about_user_middle_name_user_number_student_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=128, verbose_name="Отчество"),
        ),
    ]
