# Generated by Django 4.2.3 on 2023-07-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_speciality_id_timenorm_speciality"),
        ("user", "0011_alter_user_middle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="educationBase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.educationbase",
            ),
        ),
    ]
