# Generated by Django 4.2.3 on 2023-09-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_speciality_id_timenorm_speciality"),
        ("user", "0012_alter_user_educationbase"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="speciality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.speciality",
                verbose_name="Специальность",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="academicDegree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.academicdegree",
                verbose_name="Ученая степень",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="academicTitle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.academictitle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="educationBase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.educationbase",
                verbose_name="Основа обучения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.position",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="studStatus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.studstatus",
                verbose_name="Статус студента",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="studentGroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.studentgroup",
                verbose_name="Группа",
            ),
        ),
    ]
