# Generated by Django 4.2.3 on 2023-09-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_speciality_id_timenorm_speciality"),
        ("user", "0013_user_speciality_alter_user_academicdegree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="eduLevel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.edulevel",
                verbose_name="Уровень образования",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="academicTitle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.academictitle",
                verbose_name="Ученое звание",
            ),
        ),
    ]
