# Generated by Django 4.2.3 on 2023-09-08 15:17

import api.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_user_number_student_book_alter_user_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (api.constants.Role["STUDENT"], "Студент"),
                    (api.constants.Role["TEACHER"], "Преподаватель"),
                    (api.constants.Role["SPECIALIST"], "Специалист УМР"),
                ],
                default=None,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
