# Generated by Django 4.2.3 on 2023-09-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_speciality_id_timenorm_speciality"),
        ("user", "0016_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vkrHours",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.vkrhours",
                verbose_name="Часы на ВКР",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="academicTitle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.academictitle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="number_student_book",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.position",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[(1, "Студент")], default=None, null=True, verbose_name="Роль"
            ),
        ),
    ]
