# Generated by Django 4.2.3 on 2023-09-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_speciality_id_timenorm_speciality"),
        ("user", "0017_user_vkrhours_alter_user_academictitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teacherGroups",
            field=models.ManyToManyField(
                related_name="teacher_groups",
                to="api.studentgroup",
                verbose_name="Группы преподавателя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[(1, "Студент"), (2, "Преподаватель"), (3, "Специалист УМР")],
                default=None,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
