# Generated by Django 4.2.3 on 2023-09-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_ticketstatus_options_alter_studentgroup_course_and_more"),
        ("user", "0018_user_teachergroups_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="studentGroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_group",
                to="api.studentgroup",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="vkrHours",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.vkrhours",
                verbose_name="Часы на ВКР",
            ),
        ),
    ]
