# Generated by Django 4.2.3 on 2023-09-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_alter_user_studentgroup_alter_user_vkrhours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="teacherGroups",
        ),
    ]
