# Generated by Django 4.2.3 on 2023-10-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultancytype",
            options={
                "ordering": ["-id"],
                "verbose_name": "Вид работы",
                "verbose_name_plural": "Вид консультации",
            },
        ),
    ]
