# Generated by Django 4.2.3 on 2023-10-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="graduation",
            constraint=models.UniqueConstraint(
                models.F("graduation_type"),
                models.F("year"),
                name="graduation_type_unique",
                violation_error_message="Такой выпуск уже существует",
            ),
        ),
    ]
