# Generated by Django 4.2.3 on 2023-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="message",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="comment",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Комментарий"
            ),
        ),
    ]
