# Generated by Django 4.2.3 on 2023-07-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_ticketstatus_ticket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-id"],
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
            },
        ),
    ]
