# Generated by Django 4.2.3 on 2023-10-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_graduation_graduation_type_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="speciality",
            field=models.ForeignKey(
                default=30,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.speciality",
                verbose_name="Специальность",
            ),
            preserve_default=False,
        ),
    ]
