# Generated by Django 4.2.3 on 2023-07-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_ticket_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicDegree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Название ученой степени"
                    ),
                ),
            ],
            options={
                "verbose_name": "Степень",
                "verbose_name_plural": "Степени",
                "db_table": "academic_degree",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AcademicTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Название звания"),
                ),
            ],
            options={
                "verbose_name": "Звание",
                "verbose_name_plural": "Звания",
                "db_table": "acad_title",
                "ordering": ["-id"],
            },
        ),
    ]
