# Generated by Django 4.2.3 on 2023-07-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_academicdegree_academictitle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicdegree",
            options={
                "ordering": ["-id"],
                "verbose_name": "Ученая степень",
                "verbose_name_plural": "Ученые степени",
            },
        ),
        migrations.AlterModelOptions(
            name="academictitle",
            options={
                "ordering": ["-id"],
                "verbose_name": "Ученое звание",
                "verbose_name_plural": "Ученые звания",
            },
        ),
        migrations.AlterField(
            model_name="academictitle",
            name="name",
            field=models.CharField(
                max_length=128, verbose_name="Название ученого звания"
            ),
        ),
    ]
