# Generated by Django 4.2.3 on 2023-07-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_academicdegree_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="academictitle",
            table="academic_title",
        ),
    ]
