# Generated by Django 4.2.3 on 2023-07-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_academictitle_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Название основы обучения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Основа обучения",
                "verbose_name_plural": "Основы обучения",
                "db_table": "education_base",
                "ordering": ["-id"],
            },
        ),
    ]
