# Generated by Django 4.2.3 on 2023-07-17 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0008_educationbase"),
    ]

    operations = [
        migrations.CreateModel(
            name="VkrHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Название часов на ВКР"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Год")),
                ("hours", models.IntegerField(verbose_name="Часы")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Часы на ВКР",
                "verbose_name_plural": "Часы на ВКР",
                "db_table": "vkr_hours",
                "ordering": ["-id"],
            },
        ),
    ]
