# Generated by Django 4.2.3 on 2023-07-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_vkrhours"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vkrhours",
            old_name="user",
            new_name="user_id",
        ),
    ]
