# Generated by Django 4.2.3 on 2023-07-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_user_vkrhours_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Статус студента"),
                ),
            ],
            options={
                "verbose_name": "Статус студента",
                "verbose_name_plural": "Статусы студентов",
                "db_table": "student_status",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="academicdegree",
            name="abbreviation",
            field=models.CharField(
                default="аббревиатура",
                max_length=128,
                verbose_name="Сокращенное название ученой степени",
            ),
        ),
        migrations.AddField(
            model_name="academictitle",
            name="abbreviation",
            field=models.CharField(
                default="аббревиатура",
                max_length=128,
                verbose_name="Сокращенное название ученого звания",
            ),
        ),
    ]
