# Generated by Django 4.2.3 on 2023-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_worktype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.CharField(max_length=128, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Консультирование",
                "verbose_name_plural": "Консультирования",
                "db_table": "consultancy",
                "ordering": ["-id"],
            },
        ),
    ]
