# Generated by Django 4.2.3 on 2023-07-18 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0014_consultancy_student_consultancy_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancy",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studentt",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacherr",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
