# Generated by Django 4.2.3 on 2023-07-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_consultancy_student_alter_consultancy_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="EduForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Форма обучения"),
                ),
            ],
            options={
                "verbose_name": "Форма обучения",
                "verbose_name_plural": "Формы обучения",
                "db_table": "edu_form",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EduLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Уровень образования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Уровень образования",
                "verbose_name_plural": "Уровни образования",
                "db_table": "edu_level",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Graduation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typeGraduation",
                    models.CharField(max_length=128, verbose_name="Тип выпуска"),
                ),
                ("year", models.IntegerField(verbose_name="Год")),
            ],
            options={
                "verbose_name": "Выпуск",
                "verbose_name_plural": "Выпуски",
                "db_table": "graduation",
                "ordering": ["-id"],
            },
        ),
    ]
