# Generated by Django 4.2.3 on 2023-07-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_eduform_edulevel_graduation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=128, verbose_name="Код специальности"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Название специальности"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=128,
                        verbose_name="Сокращенное название специальности",
                    ),
                ),
                (
                    "edulevel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.edulevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
                "db_table": "speciality",
                "ordering": ["-id"],
            },
        ),
    ]
