# Generated by Django 4.2.3 on 2023-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_studentgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="number",
            field=models.IntegerField(verbose_name="Номер группы"),
        ),
    ]
