# Generated by Django 4.2.3 on 2023-07-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_studentgroup_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeNorm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.IntegerField(verbose_name="Количество часов")),
                (
                    "graduation_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.graduation",
                    ),
                ),
                (
                    "speciality_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.speciality",
                    ),
                ),
                (
                    "workType",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.worktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Норма времени",
                "verbose_name_plural": "Нормы времени",
                "db_table": "time_norm",
                "ordering": ["-id"],
            },
        ),
    ]
