# Generated by Django 4.2.3 on 2023-07-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_position_name_alter_ticketstatus_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="dt_send",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата отправки заявки"
            ),
        ),
    ]
