# Generated by Django 4.2.3 on 2023-07-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_ticket_dt_send"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vkrhours",
            name="name",
        ),
    ]
