# Generated by Django 4.2.3 on 2023-07-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_vkrhours_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timenorm",
            old_name="speciality_id",
            new_name="speciality",
        ),
    ]
