# Generated by Django 4.2.3 on 2023-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_speciality_id_timenorm_speciality"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketstatus",
            options={},
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="course",
            field=models.IntegerField(verbose_name="Курс"),
        ),
        migrations.AlterField(
            model_name="ticketstatus",
            name="name",
            field=models.IntegerField(
                choices=[(1, "Новая"), (2, "Принятая"), (3, "Отклонена")],
                default=None,
                null=True,
                verbose_name="Статус заявки",
            ),
        ),
        migrations.AlterModelTable(
            name="ticketstatus",
            table=None,
        ),
    ]
