# Generated by Django 4.2.3 on 2023-09-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_ticket_ticketstatus_delete_ticketstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="ticketStatus",
        ),
    ]
