# Generated by Django 4.2.3 on 2023-09-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_remove_ticket_ticketstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticketStatus",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
