# Generated by Django 4.2.3 on 2023-09-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_ticket_ticketstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name="Название статуса заявки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус заявки",
                "verbose_name_plural": "Статусы заявок",
                "db_table": "ticket_status",
                "ordering": ["-id"],
            },
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticketStatus",
            field=models.IntegerField(
                choices=[(1, "Новая"), (2, "Принятая"), (3, "Отклонено")],
                default=1,
                verbose_name="Статус заявки",
            ),
        ),
    ]
